#This is the configuration file for updating device settings
#For more information check https://developer.cisco.com/meraki/api-v1/update-device/

devices:
  - serial: "AAAA-BBBB-CCCC"
    name: "My_device"
    tags:
      - "tag1"
      - "tag2"
    notes: ""
    moveMapMarker: true
    #address: ""
    #floorPlanId: ""
    #switchProfileId: ""
    #lat: 37.4180951010362
    #lng: -122.098531723022